; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Mar 25 2020 07:52:59 GMT+0100 (Central European Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


