; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Mar 25 2020 07:52:59 GMT+0100 (Central European Standard Time)
M280 P0 S10 ; deploy BLTouch

