; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Mar 25 2020 07:53:00 GMT+0100 (Central European Standard Time)
M280 P0 S90 ; retract BLTouch

