; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Mar 25 2020 07:53:00 GMT+0100 (Central European Standard Time)

