; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Mar 25 2020 07:53:00 GMT+0100 (Central European Standard Time)
; Wait for set temperatures to be reached
M116 P0

