; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Mon May 18 2020 20:36:22 GMT+0200 (Central European Summer Time)
M280 P0 S10 ; deploy BLTouch

