; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Mon May 18 2020 20:36:22 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

